### ISSUE TITLE
Issue with build android app

### ISSUE THREAD

**Issue by jannikbuschke** [Nohac/redux-persist-expo-fs-storage#3] opened 2019-09-03 09:15 UTC
Hi thanks for your library.
When running my application inside expo persistence works fine.
However when I build the android bundle and execute it as a normal app my redux store always starts with an initial state.

Any ideas what could be wrong?

using
```
    "expo": "33.0.7",
    "expo-file-system": "5.0.1",
    "redux-persist-expo-fs-storage": "2.0.0",
```
and
```js
export const persistedRootReducer = persistReducer(
  {
    key: "reduxstore",
    keyPrefix:"",
    stateReconciler: autoMergeLevel2,
    storage: FSStorage(),
  },
  rootReducer,
)

```

**Comment by Nohac** [comment] 2019-09-03 10:38
I'm not entirely sure what the issue is, and I got to admit that I've never used this with redux before (only apollo).
However, did you try to run the [persistor](https://github.com/rt2zz/redux-persist/#persistor-object) to persist the state, then reload the app?

**Comment by Nohac** [comment] 2019-09-12 10:25
Closing this issue for now, feel free to reopen if this is still an issue.

**Closed as completed** 2019-09-12 10:25 UTC
